version: '3.8'

services:
  postgres:
    image: postgres
    container_name: brabosburger-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: brabosburger
    volumes:
      - pgdata:/var/lib/postgresql/data

  mongo:
    image: mongo
    container_name: brabosburger-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

volumes:
  pgdata:
  mongodata:
